---
name: Tests
on:
  push:
    branches:
      - "main"
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - "3.1"
          - "3.2"
          - "3.3"

    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Install Appraisal dependencies
        run: bundle exec appraisal install
      - name: Set up the database
        run: bundle exec rails db:setup
      - name: Run tests
        run: bundle exec rails test
      - name: Appraise Rails 6.1
        run: bundle exec appraisal rails-6-1 rails test
      - name: Appraise Rails 7.0
        run: bundle exec appraisal rails-7-0 rails test
      - name: Appraise Rails 7.2
        run: bundle exec appraisal rails-7-2 rails test
